version: 0.2

phases:
  install:
    commands:
      - echo Installing httpd
      - sudo yum update -y
      - sudo yum install httpd -y
      - sudo systemctl start httpd
  build:
    commands:
      - echo Build started on $(date)
  post_build:
    commands:
      - echo Configuring httpd

artifacts:
  files:
    - '**/*'




