version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y httpd
  build:
    commands:
      - echo Copying files...
      - cp app/index.html /var/www/html/
      - cp app/style.css /var/www/html/
      - cp -r images/ /var/www/html/images/  # Make sure images are copied to the correct directory
  post_build:
    commands:
      - echo Build and copy complete.
artifacts:
  files:
    - '**/*'  # Make sure this includes the images folder and other necessary files


