version: 0.2

phases:
  install:
    commands:
      - echo Installing httpd
      - sudo yum update -y
      - sudo yum install -y httpd
  build:
    commands:
      - echo Build started on $(date)
      - sudo httpd -k start  # Start httpd in the foreground, as systemctl won't work
  post_build:
    commands:
      - echo Configuring httpd

artifacts:
  files:
    - '**/*'




