version: 0.2

phases:
  install:
    commands:
      - echo Installing Apache HTTP server...
      - yum update -y
      - yum install -y httpd
  build:
    commands:
      - echo Building and copying files...
      - cp app/index.html /var/www/html/
      - cp app/style.css /var/www/html/
      - cp -r images/ /var/www/html/images/
      - systemctl start httpd
  post_build:
    commands:
      - echo Deployment successful!

artifacts:
  files:
    - '**/*'

